"""init

Revision ID: 441476cdcb12
Revises: 
Create Date: 2026-03-12 11:14:35.331856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441476cdcb12'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建用户表
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('timers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('once', 'daily', name='timer_type'), nullable=False),
    sa.Column('status', sa.Enum('enabled', 'completed', 'deleted', name='timer_status'), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.Time(), nullable=True),
    sa.Column('fire_at', sa.DateTime(), nullable=True),
    sa.Column('next_fire_at', sa.DateTime(), nullable=True),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status_next_fire', 'timers', ['status', 'next_fire_at'], unique=False)
    op.create_index('idx_user_status', 'timers', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_timers_fire_at'), 'timers', ['fire_at'], unique=False)
    op.create_index(op.f('ix_timers_next_fire_at'), 'timers', ['next_fire_at'], unique=False)
    op.create_index(op.f('ix_timers_user_id'), 'timers', ['user_id'], unique=False)
    op.create_table('timer_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timer_id', sa.Integer(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['timer_id'], ['timers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_fired', 'timer_events', ['user_id', 'fired_at'], unique=False)
    op.create_index('idx_user_read', 'timer_events', ['user_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_timer_events_fired_at'), 'timer_events', ['fired_at'], unique=False)
    op.create_index(op.f('ix_timer_events_read_at'), 'timer_events', ['read_at'], unique=False)
    op.create_index(op.f('ix_timer_events_timer_id'), 'timer_events', ['timer_id'], unique=False)
    op.create_index(op.f('ix_timer_events_user_id'), 'timer_events', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # 创建默认用户
    op.execute("""
        INSERT INTO users (username, password_hash, created_at)
        VALUES
            ('admin', '$2b$12$oE.mRJmq8H.xCybeoqPHwOmVG3XwxQka/Rk7LSnbNA9VMr3m3FIya', now()),
            ('user', '$2b$12$NUozO8QnoLqoh2BTCqdXZ.zXgxEzuPX9jCkgUG1prsszqdjzAVe6m', now())
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timer_events_user_id'), table_name='timer_events')
    op.drop_index(op.f('ix_timer_events_timer_id'), table_name='timer_events')
    op.drop_index(op.f('ix_timer_events_read_at'), table_name='timer_events')
    op.drop_index(op.f('ix_timer_events_fired_at'), table_name='timer_events')
    op.drop_index('idx_user_read', table_name='timer_events')
    op.drop_index('idx_user_fired', table_name='timer_events')
    op.drop_table('timer_events')
    op.drop_index(op.f('ix_timers_user_id'), table_name='timers')
    op.drop_index(op.f('ix_timers_next_fire_at'), table_name='timers')
    op.drop_index(op.f('ix_timers_fire_at'), table_name='timers')
    op.drop_index('idx_user_status', table_name='timers')
    op.drop_index('idx_status_next_fire', table_name='timers')
    op.drop_table('timers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('idx_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

    # 删除默认用户
    op.execute("DELETE FROM users WHERE username IN ('admin', 'user')")
